version: "3"
services:
  postgres:
    image: postgres
    container_name: know_your_language_db
    environment:
      POSTGRES_PASSWORD: "Postgres999"
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data